version: 2.1

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install
      - run:
          name: Run Rubocop
          command: |
            rubocop

  test:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install
      - run:
          name: Run RSpec tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - rubocop
      - test:
          requires:
            - rubocop
